use axum::{
    routing::get,
    Router,
    response::{Html, IntoResponse},
    http::StatusCode,
};
use tower_http::services::ServeDir;
use std::net::SocketAddr;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

#[tokio::main]
async fn main() {
    // Initialize tracing
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "ltd_portfolio=debug,tower_http=debug".into()),
        )
        .with(tracing_subscriber::fmt::layer())
        .init();

    // Build our application with routes
    let app = Router::new()
        // 1. Serve the 'assets' folder generated by Vite (JS/CSS/Images)
        .nest_service("/assets", ServeDir::new("client/dist/assets"))
        
        // 2. Serve specific static files that might sit in the root of dist (like vite.svg)
        .nest_service("/vite.svg", ServeDir::new("client/dist/vite.svg"))

        // 3. Main entry point - serve index.html at root
        .route("/", get(serve_index))

        // 4. FALLBACK: Serve index.html for any other route (e.g. /portfolio, /about)
        // This allows React Router to handle the page routing on the client side
        .fallback(get(serve_index)); 

    // Run the server
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::info!("🚀 Server starting on http://{}", addr);
    tracing::info!("📁 Serving static files from ./client/dist");
    tracing::info!("🌐 Visit http://localhost:3000 to view your portfolio");
    
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

// Single handler to serve the React entry point
async fn serve_index() -> impl IntoResponse {
    match tokio::fs::read_to_string("client/dist/index.html").await {
        Ok(content) => (StatusCode::OK, Html(content)),
        Err(_) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Html("<h1>Error: client/dist/index.html not found. Did you run 'npm run build'?</h1>".to_string()),
        ),
    }
}